# Book settings
title: ComModHOS
author: TU Delft Offshore Engineering
copyright: "2023"
logo: "images/logo/TU_logo.png"

# description: >- # this means to ignore newlines until "baseurl:"
#   This is a collection of note and examples in numerical computations.

execute:
  timeout: 120
  execute_notebooks: auto
  exclude_patterns: #[_build, Thumbs.db, .DS_Store, LICENSE.md, w1_t1]
      - '_build'
      - 'Thumbs.db'
      - '.DS_Store'
      #- "**.ipynb_checkpoints"
      - 'LICENSE.md'
      - 'w1_t1.ipynb'
      - 'w2_t2.ipynb'
      - 'w2_t3.ipynb'
      - 'w4_t1.ipynb'
      - 'w4_t2.ipynb'
      - 'w5_t1.ipynb'
      - 'w6_t1.ipynb'

# Bibliography settings
bibtex_bibfiles:
  - references.bib

# html:
#   baseurl: https://kyleniemeyer.github.io/computational-thermo
#   home_page_in_navbar: true
#   use_repository_button: true

repository:
  url: https://github.com/TUDelft-CITG/ComModHOS.git
  branch: master
  path_to_book: "book"

# launch_buttons:
#   binderhub_url: "https://mybinder.org"
#   thebelab: true

# binder:
#   binderhub_url: "https://mybinder.org"
#   text: "Launch binder"

sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    html_show_copyright: false
    mathjax3_config:
      TeX:
        Macros:
          vector: ["\\vec{#1}", 1]
          uvec: ["\\hat{#1}", 1]
          mag: ["\\lVert#1\\rVert", 1]
          cross: "\\times"
          unit: ["#1~\\mathrm{#2}", 2]
    # MathJax 3 + Sphinx cannot currently use custom macros as defined here
    # See: https://github.com/executablebooks/jupyter-book/issues/963
    # and: https://github.com/executablebooks/jupyter-book/issues/917
    # mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    - replacements
    - smartquotes
    #- substitution

latex:
  latex_documents:
    targetname: book.tex
  latex_engine: xelatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
